# Permalinks
permalink: pretty

# Setup
title: Sebastian Bird
tagline: 'A personal portfolio'
description: 'A little about me.'
url: http://everdeep.github.io
baseurl: /

# author:
#     name: 'Sebastian Bird'
#     url: http://everdeep.github.io

paginate: 5

# Custom vars
# version: 1.0.0

# github:
#     repo: https://github.com/everdeep/everdeep.github.io

safe: true
lsi: false
gems: [jekyll-gist, jekyll-paginate]